### ISSUE TITLE
Map url for databases to make them more intuitive

### ISSUE THREAD

**Issue by SantoshSrinivas79** [transitive-bullshit/nextjs-notion-starter-kit#154]
I want to map URLs for the contents of a database so that they are more intuitive.

for example:

`resumes` database should map to `http://localhost:3000/resumes/candidate_name`

`project` database should map to `http://localhost:3000/projects/project_name`

Could you pls advise the location where I could need to make these custom code changes?

I perhaps could manually set them or generate them using `pageUrlOverrides`. But, I'm more interested in doing this through code for my specific use-case

**Comment by txs** [comment]
I would like to use this too! Please give us a guide! Thanks!

**Comment by txs** [comment]
I find that since this project uses nextjs. so, it uses the nextjs router that is treating every page from notion as a page without the tree structure. Inside the pages folder you can see that all the pages are rendered by [pageId].tsx. That's why if you are going to use override. "-" is the only way to do it. If you want to have /resumes/[candidate_name].tsx you can create the structure like this inside the pages folder. However, for the [candidate_name].tsx, file you might need to rewrite how to render and how to get the data from notion. Hopefully there's a way to generate the path for writing dynamic rules for nextjs router.
