### ISSUE TITLE
Make a meta description (for SEO) for each individual page.

### ISSUE THREAD

**Issue by ilyadynin** [transitive-bullshit/nextjs-notion-starter-kit#167]
So in the code I see that there is like a variable for the meta description `content={socialDescription}` - does this fetch the Notion site and use the description there or something? What is the correct to set up individual descriptions for different pages. Or is this just a variable for the example description from the config file?

Help you can help me out :)

**Comment by txs** [comment]
Hi! I test this for you! If the page "Description" property is null, it'll use the default config.description value.  For the root page, I believe it cannot fetch the properties even though I put the page inside a database and give it a value. However, for child page, if you use collection to manage pages with a "Description" property, then, the description can be replace so that the SEO is good!

**Comment by transitive-bullshit** [comment]
This should be fixed with the latest major release.

Any page with a `Description` text property will now be used correctly instead of the default

**Comment by hilmanski** [comment]
Hi @transitive-bullshit 
thanks for this.
Can you elaborate by "Any page with a Description text property.. ?"  is it something on Notion?
I would add it to readme of this project as it's pretty important if you let me know.
Or do you mean meta desc HTML tag?
