### ISSUE TITLE
Gallery view is single column

### ISSUE THREAD

**Issue by jaypozo** [transitive-bullshit/nextjs-notion-starter-kit#288]
I created a new page with a gallery view, similar to the index page. On this new page, the rendered page lists the sub pages in a single column. 

Expected: gallery view is shown in two columns, as it is in Notion.

web page: 
https://www.filmphoto.io/cameras

![CleanShot 2022-04-28 at 16 02 04](https://user-images.githubusercontent.com/471422/165861457-340800fe-dc55-40e6-bd6c-ae2139f0a5f1.png)

Notion page:
https://jaypozo.notion.site/Cameras-461c95e6745c4dc6ac8646b50fc73198

![CleanShot 2022-04-28 at 16 02 38](https://user-images.githubusercontent.com/471422/165861507-0d4cfcec-98da-4454-9b94-4b6bfd7a66ec.png)

**Comment by transitive-bullshit** [comment]
Hmmm, https://nextjs-notion-starter-kit.transitivebullsh.it/ shows the main repo deployed without any changes.

The screenshots show that you've at least made additional changes beyond changing `rootNotionPageId` since it's using a custom header. So without knowing the full scope of additional changes, it's really difficult to try to help you.

That being said, you're welcome to tweak the CSS in https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/main/styles/notion.css to fit your needs.

**Comment by transitive-bullshit** [comment]
Ahhh I see what's going on.

Your main collection here https://www.filmphoto.io is formatted properly, but the collection on your subpage https://www.filmphoto.io/cameras isn't formatted properly, right?

I think the issue is https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/main/styles/notion.css#L20-L22

This makes the home page slightly wider so it shows two columns by default, but on other pages this doesn't take effect by default. You'll need to tweak this to fix your issue.

**Comment by jaypozo** [comment]
Great, thank you!
