### ISSUE TITLE
Vercel social images failing to generate on live

### ISSUE THREAD

**Issue by quacrobat** [transitive-bullshit/nextjs-notion-starter-kit#332]
This references "Vercel social images not found, failing to generate" #310
Fix doesn't work for me, changing the engine/node version in package.json throws an error at `vercel --prod` time.

**Comment by TetraTheta** [comment]
I think this is very complicated issue.

This project depends on `next-api-og-image` which has peer dependency of `chrome-aws-lambda`.

The problem is, size of `chrome-aws-lambda` increases of each 'releases', and it exceedes Vercel's size limit of 50MB. You might get error saying `Warning: Max serverless function size of 50 MB compressed or 250 MB uncompressed reached` in Vercel's build log. At the point of reaching 50MB size limit, no further serverless function are 'processed'. So no OG/Twitter Image is generated.

Vercel already knows about hitting 50MB size limit and there is [discussion](https://github.com/vercel/community/discussions/103) about this. 

Also, `chrome-aws-lambda` doesn't support Node.js 16.x and the project is kind of dead. Author of `chrome-aws-lambda` didn't reponded for months. There is alternative of `chrome-aws-lambda` which is [just fork of it](https://github.com/Sparticuz/chrome-aws-lambda).

So, I consider this as dependency bug.  
`chrome-aws-lambda` 'ignores' PR which add support for Node.js 16.x and it has problem with Vercel which makes serverless function size exceedes 50MB limit.

**Comment by transitive-bullshit** [comment]
This should now be fixed if you pull latest.

Also make sure auth is not enabled on your Vercel project; otherwise, social images won't work (https://github.com/transitive-bullshit/nextjs-notion-starter-kit/issues/437#issuecomment-1826206998)

Examples:

- [nextjs-notion-starter-kit.transitivebullsh.it/api/social-image?id=ca24be04-c161-415c-b5e4-015a6a9a7d44](https://nextjs-notion-starter-kit.transitivebullsh.it/api/social-image?id=ca24be04-c161-415c-b5e4-015a6a9a7d44)
- [transitivebullsh.it/api/social-image?id=3db25f36-0b1c-4591-b3e9-50e39edfb396](https://transitivebullsh.it/api/social-image?id=3db25f36-0b1c-4591-b3e9-50e39edfb396)
