### ISSUE TITLE
How to prevent unintended use of domain by others?

### ISSUE THREAD

**Issue by urnehpets** [transitive-bullshit/nextjs-notion-starter-kit#38]
Be careful! I was wondering if there was any way to prevent someone from adding their notion page onto your / my domain? Could potentially be very dangerous. For example: 

https://transitivebullsh.it/A-page-with-bad-stuff-on-it-d291bca5556e4696b96911fb1f39efde

**Comment by transitive-bullshit** [comment]
This is such an amazing example :)

Thanks so much for bringing it to my attention.

Yeah, you can definitely set the [rootNotionSpaceId](https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/main/lib/acl.ts#L41-L55) in order to restrict pages to only ones that reside in the same Notion workspace as your root page.

I'm not doing that right now because I like having the flexibility to test any notion page really quickly, but I may add it as a default soon if it starts to be abused.

**Comment by transitive-bullshit** [comment]
I just pushed a change so `rootNotionSpaceId` is exposed via `site.config.js`, and if you choose to set it, it will prevent pages from outside your workspace from resolving.

You can see what this looks like live here: https://transitivebullsh.it/A-page-with-bad-stuff-on-it-d291bca5556e4696b96911fb1f39efde

In order to find your Notion workspace ID, just load any of your site's page into your browser as you would normally, and open up the developer console. There will be a global variable that you can access called `block` which is the Notion data for the current page, and you just have to type `block.space_id` which will print out that page's workspace ID.
