### ISSUE TITLE
Unavailable Automatic Social Images

### ISSUE THREAD

**Issue by JIeJaitt** [transitive-bullshit/nextjs-notion-starter-kit#426]
#### Description
<img width="793" alt="image" src="https://user-images.githubusercontent.com/77219045/208231398-1e07130e-798c-43f5-b395-80a525bd7cac.png">

No matter what I do, the automatic social image function of this project is still unavailable. My article does not automatically generate a head image. How to use this function?
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/77219045/208231340-afb4d952-d576-4c8f-a008-3eb6ccdfa52c.png">

#### Notion Test Page ID
- Notion Test Page ID：3f0f3bfabd44413697e4d1c7ae31e6c1
- my blog：https://jiejaitt.vercel.app/

**Comment by transitive-bullshit** [comment]
This should now be fixed if you pull latest.

Also make sure auth is not enabled on your Vercel project; otherwise, social images won't work (https://github.com/transitive-bullshit/nextjs-notion-starter-kit/issues/437#issuecomment-1826206998)

Examples:

- [nextjs-notion-starter-kit.transitivebullsh.it/api/social-image?id=ca24be04-c161-415c-b5e4-015a6a9a7d44](https://nextjs-notion-starter-kit.transitivebullsh.it/api/social-image?id=ca24be04-c161-415c-b5e4-015a6a9a7d44)
- [transitivebullsh.it/api/social-image?id=3db25f36-0b1c-4591-b3e9-50e39edfb396](https://transitivebullsh.it/api/social-image?id=3db25f36-0b1c-4591-b3e9-50e39edfb396)
