### ISSUE TITLE
[Not functional] - Social images

### ISSUE THREAD

**Issue by RyRy79261** [transitive-bullshit/nextjs-notion-starter-kit#437]
#### Description

Social images are not being generated for any page and there is no insight into how these are controlled, set or generated outside of the get request in the code base

**Comment by Sai-Santosh-Pal** [comment]
@transitive-bullshit I think the API isn't functioning well

**Comment by RyRy79261** [comment]
@transitive-bullshit So I'm aware that its on the fly, however when I step through the code, its not receiving any data or generating anything, but it is loading the Notion page. Not sure what its meant to be loading into the `social-image.tsx` but yeah, cant get it to respond

**Comment by sureshHARDIYA** [comment]
I had same issue yesterday, I reduced some extra stuffs from that page like removed date, removed font, and reduced dimension of image and worked fine.

**Comment by abhidadhaniya23** [comment]
I think image generation functionality working properly well and I was facing the problem of- Image generation for social media previews are working well in development (localhost) but in production I was getting `unauthorized` as response. I find a meaningful solution where I need to change the settings of vercel for this repository and here are the changes I made.

**Please disable Vercel Authentication so that every time when you hit the end point, it'll return the generated image as response.**

![image](https://github.com/transitive-bullshit/nextjs-notion-starter-kit/assets/70057423/57204215-080a-4810-89a3-554cf895a804)

**Comment by transitive-bullshit** [comment]
This should now be fixed if you pull latest.

Examples:

- [nextjs-notion-starter-kit.transitivebullsh.it/api/social-image?id=ca24be04-c161-415c-b5e4-015a6a9a7d44](https://nextjs-notion-starter-kit.transitivebullsh.it/api/social-image?id=ca24be04-c161-415c-b5e4-015a6a9a7d44)
- [transitivebullsh.it/api/social-image?id=3db25f36-0b1c-4591-b3e9-50e39edfb396](https://transitivebullsh.it/api/social-image?id=3db25f36-0b1c-4591-b3e9-50e39edfb396)
