### ISSUE TITLE
Task timed out after 10.01 seconds

### ISSUE THREAD

**Issue by philffm** [transitive-bullshit/nextjs-notion-starter-kit#80]
Hi @transitive-bullshit 

Great project, working super reliable so far 🎉

However now after filling the page with some content, Vercel is constantly throwing me "Task timed out after 10.01 seconds". The only way to update the content right now, is to redeploy. I tried increasing the concurrency value in get-site-maps.ts, but without any luck so far. 

It is possible to create new items on the home page - but the urls / new pages are not instantly generated (need to redeploy).

![Screenshot 2021-04-02 at 17 28 42](https://user-images.githubusercontent.com/6079545/113429854-7aa8c800-93d9-11eb-88ed-3cc88b6c0a14.jpg)

https://www.notion.so/UX-Life-0aac38d9e5994f8aa7d586dec4c6883e

Do you have an idea?

Best, Phil

**Comment by transitive-bullshit** [comment]
Hey @philffm, thanks for the report & the kind words 🙏

The biggest reason it is timing out is due to https://github.com/transitive-bullshit/nextjs-notion-starter-kit/issues/58

We're currently doing a lot of unnecessary work each time a new URL alias is fetched to resolve the mapping from URL alias => notion ID.

We can definitely improve this; I'll try to get a workaround in later tonight.

See also #79.

**Comment by transitive-bullshit** [comment]
@philffm as a workaround for now, you can add `includeNotionIdInUrls: true` to your sitemap.

This will make your non-root site URLs include Notion IDs which will resolve much faster.

**Comment by transitive-bullshit** [comment]
Tracking a WIP solution here: https://github.com/transitive-bullshit/nextjs-notion-starter-kit/pull/83

**Comment by philffm** [comment]
Awesome! It just works... again! 🎉
